/** Popular US / UK films for the random-film button. */
export const POPULAR_FILMS: string[] = [
  "The Lion King",
  "Frozen",
  "Moana",
  "Toy Story",
  "Finding Nemo",
  "Shrek",
  "Harry Potter and the Philosopher's Stone",
  "The Princess Bride",
  "Notting Hill",
  "Love Actually",
  "Paddington",
  "The King's Speech",
  "Forrest Gump",
  "The Shawshank Redemption",
  "Titanic",
  "The Devil Wears Prada",
  "Legally Blonde",
  "Mean Girls",
  "Clueless",
  "Home Alone",
  "Mrs. Doubtfire",
  "Matilda",
  "Charlie and the Chocolate Factory",
  "The Parent Trap",
  "10 Things I Hate About You",
  "Pretty Woman",
  "You've Got Mail",
  "When Harry Met Sally",
  "Sleepless in Seattle",
  "The Holiday",
  "Four Weddings and a Funeral",
  "Bridget Jones's Diary",
  "The Grand Budapest Hotel",
  "Inception",
  "The Matrix",
  "Back to the Future",
  "Jurassic Park",
  "E.T. the Extra-Terrestrial",
  "The Incredibles",
  "Up",
  "WALL-E",
  "Ratatouille",
  "Coco",
  "Encanto",
  "How to Train Your Dragon",
  "The Goonies",
  "The Breakfast Club",
  "Ferris Bueller's Day Off",
  "Mamma Mia!",
  "The Greatest Showman",
  "La La Land",
  "Dead Poets Society",
  "Good Will Hunting",
  "The Pursuit of Happyness",
  "Catch Me If You Can",
  "Ocean's Eleven",
  "Mary Poppins",
  "The Sound of Music",
  "Pride & Prejudice",
  "Little Women",
  "About Time",
  "The Imitation Game",
  "Hidden Figures",
  "The Intern",
  "Julie & Julia",
  "It's a Wonderful Life",
  "Roman Holiday",
  "My Fair Lady",
  "Fantastic Mr. Fox",
  "Nanny McPhee",
  "The Blind Side",
  "Erin Brockovich",
  "Miss Congeniality",
  "The Proposal",
  "13 Going on 30",
  "50 First Dates",
  "Enchanted",
  "The Princess Diaries",
  "School of Rock",
  "Night at the Museum",
  "National Treasure",
  "The Terminal",
  "Cast Away",
  "Big",
  "Breakfast at Tiffany's",
  "The Wizard of Oz",
  "Singin' in the Rain",
  "West Side Story",
  "Chicago",
  "Atonement",
  "Sense and Sensibility",
  "Emma",
  "While You Were Sleeping",
  "My Best Friend's Wedding",
  "Jerry Maguire",
  "As Good as It Gets",
  "Rain Man",
  "A Beautiful Mind",
  "The Social Network",
  "The Theory of Everything",
  "Bohemian Rhapsody",
  "The Help",
  "Green Book",
];

export function pickRandomFilm(exclude?: string): string {
  const pool = exclude
    ? POPULAR_FILMS.filter((title) => title.toLowerCase() !== exclude.trim().toLowerCase())
    : POPULAR_FILMS;
  const list = pool.length > 0 ? pool : POPULAR_FILMS;
  return list[Math.floor(Math.random() * list.length)] ?? "The Lion King";
}
